version: "3.8"

services:

  backend:
    image: localhost/jipodhead/crewai_fastapi_litellm:v1.0.0
    privileged: true
    restart: always
    volumes:
      - ./backend/server:/app
      - ./data:/data
    working_dir: /app
    user: root
    command: bash -c "pip install -r requirements.txt && python main.py"
    ports:
      - "1500:1500"
    tty: true
    network_mode: host
    environment:
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OLLAMA_API_KEY: ${OLLAMA_API_KEY}
      OPENWEBUI_API_KEY: ${OPENWEBUI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stylegen
      POSTGRES_PASSWORD: stylegen
      POSTGRES_DB: main
    network_mode: host

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080"
    environment:
      POSTGRES_USER: stylegen
      POSTGRES_PASSWORD: stylegen
      POSTGRES_DB: main
      POSTGRES_HOST_AUTH_METHOD: trust
    network_mode: host


